元凶：
====
void asyncCloseClientOnOutputBufferLimitReached(redisClient *c) {
    redisAssert(c->reply_bytes < ULONG_MAX-(1024*64));
    if (c->reply_bytes == 0 || c->flags & REDIS_CLOSE_ASAP) return;
    if (checkClientOutputBufferLimits(c)) {
        sds client = getClientInfoString(c);

        freeClientAsync(c);
        redisLog(REDIS_WARNING,"Client %s scheduled to be closed ASAP for overcoming of output buffer limits.", client);
        sdsfree(client);
    }
}

在sync rdb过程，发现在read rdb size 或者rdb时，经常如下错
在Log中记录I/O error reading bulk count from MASTER: Resource temporarily unavailable，查找相应函数

readSyncBulkPayload函数中
if (syncReadLine(fd,buf,1024,server.repl_syncio_timeout*1000) == -1) {
            redisLog(REDIS_WARNING,
                "I/O error reading bulk count from MASTER: %s",
                strerror(errno));
            goto error;
}


调用syncio.c中的syncRead，Resource temporarily unavailable这个message看不出什么门道，后来在redisLog添加nread，发现nread=0时就会抛出这个错误。
nread=read(),nread=0,也就是说epoll返回了EPOLLIN事件但读到数据个数为0，问度娘得知，这是对方主动关闭的原因。
可以一直以为是master<->slave 心跳连接超时导致。但从master的log也没有看到相关日志。快下班了又仔细看了一下log
[23148] 04 Jun 15:43:10.986 # Client addr=10.103.51.60:14846 fd=26 name= age=21 idle=21 flags=S db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=16121 oll=10446 
omem=268435504 events=rw cmd=psync scheduled to be closed ASAP for overcoming of output buffer limits.

